/**
 * LIVE full-session walkthrough — runs the REAL SessionEngine through one
 * complete PRD §5 loop (BASELINE → INTENTION → ENCOUNTER → GROWTH) and prints the
 * actual cue spoken at each stage, in order, with every cue generated by the live
 * Anthropic API.
 *
 *   # set ANTHROPIC_API_KEY first (see README "Live smoke test"), then:
 *   node --env-file-if-exists=.env src/examples/runLiveSession.ts
 *
 * How it forces live generation at EVERY stage: the engine's default source is
 * the static cue corpus, and it only asks the LLM generator when the corpus has
 * no cue for a state. So we hand it an EMPTY CueBank — every state misses, and
 * every stage's cue is produced live by `new AnthropicCueGenerator()` (the exact
 * production generator, reading ANTHROPIC_API_KEY). This is the real state
 * machine, the real lifecycle, the real triggers — only the cue *text* is live.
 *
 * Timing: virtual time (ManualClock) drives the engine's lifecycle timers
 * instantly, while a small real delay between advances lets each live API call
 * resolve. The intensity curve ramps hard early so the temporal tipping point
 * lands a few seconds in, keeping the whole walkthrough short.
 */

import { createCompanion } from '../create-companion.ts';
import { AnthropicCueGenerator } from '../generative/anthropic-cue-generator.ts';
import { ManualClock } from '../adapters/manual-clock.ts';
import { ConsoleTTS } from '../adapters/console-tts.ts';
import { MemoryEventBus } from '../adapters/memory-event-bus.ts';
import { CueBank } from '../cue-bank/cue-bank.ts';
import { isSpeakable } from '../generative/output-vocabulary.ts';
import type { EngineEvent } from '../domain/events.ts';
import type { Cue } from '../domain/cue.ts';
import type { SessionConfig } from '../domain/session.ts';

const realSleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const tick = (): Promise<void> => new Promise((r) => setImmediate(r));

/** Human label + one-line meaning for each stage, in lifecycle order. */
const STAGE_NOTE: Record<string, string> = {
  BASELINE: 'establish the physical fact of capability; neutralise self-doubt',
  INTENTION: 'direct the focus, arm the triggers, then go silent and monitor',
  ENCOUNTER: 'the tipping point — hijack the escape, command a physical override',
  GROWTH: 'consolidate the new capacity and demand the next edge',
};

interface CapturedCue {
  state: string;
  origin: 'database' | 'generated' | 'fallback';
  cue: Cue;
  gen?: { status: string; attempts: number; networkRetries: number; reason?: string };
}

async function main(): Promise<void> {
  if (!process.env['ANTHROPIC_API_KEY']) {
    console.error('✖ ANTHROPIC_API_KEY is not set. Set it (see README "Live smoke test") and re-run.');
    process.exit(2);
  }

  const clock = new ManualClock();
  const bus = new MemoryEventBus();

  // Empty corpus → every state misses → every cue comes from the live generator.
  const { engine } = createCompanion({
    clock,
    bus,
    tts: new ConsoleTTS({ log: () => {} }), // we render the cues ourselves, below
    cueBank: new CueBank([]),
    cueGenerator: new AnthropicCueGenerator(), // the real production generator
  });

  // Collect the live-generation outcome per stage so we can pair it with the cue.
  const lastGen = new Map<string, CapturedCue['gen']>();
  const captured: CapturedCue[] = [];

  bus.on((e: EngineEvent) => {
    switch (e.type) {
      case 'STATE_CHANGED':
        console.log(`\n── ${e.to}  (round ${e.round}) ────────────────────────────`);
        console.log(`   ${STAGE_NOTE[e.to] ?? ''}`);
        break;
      case 'TIPPING_POINT':
        console.log(
          `   ⚡ tipping point via ${e.source} @ intensity ${e.intensity.toFixed(2)} (${e.reason})`,
        );
        break;
      case 'CUE_GENERATION':
        lastGen.set(e.state, {
          status: e.status,
          attempts: e.attempts,
          networkRetries: e.networkRetries,
          reason: e.reason,
        });
        break;
      case 'CUE_SELECTED': {
        const rec: CapturedCue = {
          state: e.state,
          origin: e.origin,
          cue: e.cue,
          gen: lastGen.get(e.state),
        };
        captured.push(rec);
        const tag =
          rec.origin === 'generated'
            ? `live-generated${rec.gen ? ` (attempts ${rec.gen.attempts}, net-retries ${rec.gen.networkRetries})` : ''}`
            : rec.origin;
        console.log(`   ▶ CUE [${tag}]`);
        console.log(`     "${e.cue.AudioTranscript}"`);
        console.log(`     tone: ${e.cue.DeliveryTone}`);
        break;
      }
      case 'RECALIBRATED':
        console.log(`   ↺ recalibrated — ${e.stabilized ? 'STABILIZED' : 're-cue'}`);
        break;
      case 'ROUND_CLEARED':
        console.log(`   ✓ round ${e.round} cleared`);
        break;
      case 'ERROR':
        console.log(`   ! error [${e.scope}] ${e.message}`);
        break;
      case 'SESSION_ENDED':
        console.log(`\n■ session ended (${e.reason}) after ${e.rounds} round(s)`);
        break;
      default:
        break;
    }
  });

  const config: SessionConfig = {
    // A short, hard finishing set: ramps to near-max within seconds so the
    // temporal tipping point lands quickly. (Real product would use the user's
    // actual length/curve; this is compressed for the walkthrough.)
    lengthMs: 120_000,
    curve: {
      kind: 'custom',
      points: [
        { at: 0, intensity: 0.35 },
        { at: 0.02, intensity: 0.9 },
        { at: 1, intensity: 1.0 },
      ],
    },
    difficultyThresholds: [0.8], // crossed early → one ENCOUNTER tip a few % in
    enableBiometrics: false, // V1 temporal path
    maxRounds: 1, // one full BASELINE→INTENTION→ENCOUNTER→GROWTH pass
  };

  console.log('▶ Starting a live simulated session — every cue is generated by the live API.\n');
  console.log(`   length: ${config.lengthMs / 1000}s · curve: hard early ramp · trigger: temporal (V1)`);

  engine.start(config);

  // Drive virtual time forward, pausing in real time between advances so each
  // live API call can resolve before the next lifecycle timer needs to fire.
  // Self-correcting: if a call is slow, the next advance is a no-op and we retry.
  // The step budget bounds total wall time (≈ MAX_STEPS × REAL_DELAY_MS) without
  // any nondeterministic clock read.
  const REAL_DELAY_MS = 700;
  const VIRTUAL_STEP_MS = 5_000;
  const MAX_STEPS = 220; // ≈ 150s ceiling at 700ms/step

  await tick();
  for (let step = 0; bus.ofType('SESSION_ENDED').length === 0; step++) {
    if (step >= MAX_STEPS) {
      console.error('\n✖ Step budget exhausted before the session ended (network too slow?).');
      engine.stop();
      break;
    }
    await realSleep(REAL_DELAY_MS);
    clock.advance(VIRTUAL_STEP_MS);
    await tick();
  }

  // ── Final ordered summary ─────────────────────────────────────────────────
  console.log('\n\n══════════ FULL CUE SEQUENCE (in order) ══════════');
  const order = ['BASELINE', 'INTENTION', 'ENCOUNTER', 'GROWTH'];
  let allLiveAndClean = true;
  captured
    .slice()
    .sort((a, b) => order.indexOf(a.state) - order.indexOf(b.state))
    .forEach((rec, i) => {
      const live = rec.origin === 'generated';
      const clean = isSpeakable(rec.cue.AudioTranscript);
      if (!live || !clean) allLiveAndClean = false;
      console.log(`\n${i + 1}. ${rec.state}  —  ${STAGE_NOTE[rec.state] ?? ''}`);
      console.log(`   spoken:  "${rec.cue.AudioTranscript}"`);
      console.log(`   tone:    ${rec.cue.DeliveryTone}`);
      console.log(`   lever:   ${rec.cue.PhysicalLever}`);
      console.log(`   vector:  ${rec.cue.EnergeticVector}`);
      console.log(`   yield:   ${rec.cue.StructuralYield}`);
      console.log(
        `   source:  ${rec.origin}${live ? ' (live API)' : ''} · spoken-vocabulary guard: ${clean ? 'clean ✔' : 'LEAK ✖'}`,
      );
    });

  console.log('\n══════════════════════════════════════════════════');
  if (captured.length === 4 && allLiveAndClean) {
    console.log('✔ All four stages fired in order, each cue generated live and clean.');
  } else {
    console.log(
      `⚠ Captured ${captured.length}/4 stages; some were not live-generated or failed the vocabulary guard (see above).`,
    );
  }
}

void main().catch((err: unknown) => {
  console.error('\n✖ Live session threw:', err instanceof Error ? err.message : err);
  process.exit(1);
});
